apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 651109015678.dkr.ecr.ap-northeast-2.amazonaws.com/svelte-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # NLB 생성
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173
  type: LoadBalancer
